version: '3.6'
services:
  rc_mysql_cont:
    image: mysql:5.7.29
    container_name: rc_mysql_cont
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: radio_config
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - rc_mysql_cont
    environment:
      PMA_HOST: rc_mysql_cont
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  radio_mgmt_server:
    build:
      context: ./server
      target: radio_mgmt_server
    ports:
      - "18080:8080"
    depends_on:
      - rc_mysql_cont
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080 --reload
    #command: uvicorn openapi_server.main:app --host 172.16.10.37 --port 8080 --reload

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 32017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=r00tusEr
      - MONGO_INITDB_ROOT_PASSWORD=r00tpAss
    volumes:
      - ./mongodb-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 18081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=r00tusEr
      - ME_CONFIG_MONGODB_ADMINPASSWORD=r00tpAss
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
volumes:
  dbdata:
