# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class EntityRef(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EntityRef - a model defined in OpenAPI

        id: The id of this EntityRef.
        href: The href of this EntityRef [Optional].
        name: The name of this EntityRef [Optional].
        base_type: The base_type of this EntityRef [Optional].
        schema_location: The schema_location of this EntityRef [Optional].
        type: The type of this EntityRef [Optional].
        referred_type: The referred_type of this EntityRef [Optional].
    """

    id: str
    href: Optional[AnyUrl] = None
    name: Optional[str] = None
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = None
    referred_type: Optional[str] = None

EntityRef.update_forward_refs()
