# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class TimePeriod(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TimePeriod - a model defined in OpenAPI

        end_date_time: The end_date_time of this TimePeriod [Optional].
        start_date_time: The start_date_time of this TimePeriod [Optional].
    """

    end_date_time: Optional[datetime] = None
    start_date_time: Optional[datetime] = None

TimePeriod.update_forward_refs()
