# coding: utf-8

"""
    API Resource Inventory Management

    ## TMF API Reference: TMF639 - Resource Inventory   ### Release : 19.5 - December 2019  Resource Inventory  API goal is to provide the ability to manage Resources.  ### Operations Resource Inventory API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events

    The version of the OpenAPI document: 4.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.events_subscription_api import router as EventsSubscriptionApiRouter
from openapi_server.apis.notification_listeners__client_side_api import router as NotificationListenersClientSideApiRouter
from openapi_server.apis.resource_api import router as ResourceApiRouter

app = FastAPI(
    title="API Resource Inventory Management",
    description="## TMF API Reference: TMF639 - Resource Inventory   ### Release : 19.5 - December 2019  Resource Inventory  API goal is to provide the ability to manage Resources.  ### Operations Resource Inventory API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity (for administration purposes) - Manage notification of events",
    version="4.0.0",
)

app.include_router(EventsSubscriptionApiRouter)
app.include_router(NotificationListenersClientSideApiRouter)
app.include_router(ResourceApiRouter)
