# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.quantity import Quantity
from openapi_server.models.time_period import TimePeriod


class Attachment(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Attachment - a model defined in OpenAPI

        id: The id of this Attachment [Optional].
        href: The href of this Attachment [Optional].
        attachment_type: The attachment_type of this Attachment [Optional].
        content: The content of this Attachment [Optional].
        description: The description of this Attachment [Optional].
        mime_type: The mime_type of this Attachment [Optional].
        name: The name of this Attachment [Optional].
        url: The url of this Attachment [Optional].
        size: The size of this Attachment [Optional].
        valid_for: The valid_for of this Attachment [Optional].
        base_type: The base_type of this Attachment [Optional].
        schema_location: The schema_location of this Attachment [Optional].
        type: The type of this Attachment [Optional].
    """

    id: Optional[str] = None
    href: Optional[AnyUrl] = None
    attachment_type: Optional[str] = None
    content: Optional[str] = None
    description: Optional[str] = None
    mime_type: Optional[str] = None
    name: Optional[str] = None
    url: Optional[AnyUrl] = None
    size: Optional[Quantity] = None
    valid_for: Optional[TimePeriod] = None
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = None

Attachment.update_forward_refs()
