# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Entity(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Entity - a model defined in OpenAPI

        id: The id of this Entity [Optional].
        href: The href of this Entity [Optional].
        base_type: The base_type of this Entity [Optional].
        schema_location: The schema_location of this Entity [Optional].
        type: The type of this Entity [Optional].
    """

    id: Optional[str] = None
    href: Optional[AnyUrl] = None
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = None

Entity.update_forward_refs()
