# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class Extensible(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Extensible - a model defined in OpenAPI

        base_type: The base_type of this Extensible [Optional].
        schema_location: The schema_location of this Extensible [Optional].
        type: The type of this Extensible [Optional].
    """

    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = None

Extensible.update_forward_refs()
