# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401
from openapi_server.models.resource_delete_event_payload import ResourceDeleteEventPayload


class ResourceDeleteEvent(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceDeleteEvent - a model defined in OpenAPI

        event: The event of this ResourceDeleteEvent [Optional].
        event_id: The event_id of this ResourceDeleteEvent [Optional].
        event_time: The event_time of this ResourceDeleteEvent [Optional].
        event_type: The event_type of this ResourceDeleteEvent [Optional].
        correlation_id: The correlation_id of this ResourceDeleteEvent [Optional].
        domain: The domain of this ResourceDeleteEvent [Optional].
        title: The title of this ResourceDeleteEvent [Optional].
        description: The description of this ResourceDeleteEvent [Optional].
        priority: The priority of this ResourceDeleteEvent [Optional].
        time_ocurred: The time_ocurred of this ResourceDeleteEvent [Optional].
    """

    event: Optional[ResourceDeleteEventPayload] = None
    event_id: Optional[str] = None
    event_time: Optional[datetime] = None
    event_type: Optional[str] = None
    correlation_id: Optional[str] = None
    domain: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    priority: Optional[str] = None
    time_ocurred: Optional[datetime] = None

ResourceDeleteEvent.update_forward_refs()
