# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401



class ResourceRelationship(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceRelationship - a model defined in OpenAPI

        id: The id of this ResourceRelationship [Optional].
        href: The href of this ResourceRelationship [Optional].
        relationship_type: The relationship_type of this ResourceRelationship.
        resource: The resource of this ResourceRelationship.
        base_type: The base_type of this ResourceRelationship [Optional].
        schema_location: The schema_location of this ResourceRelationship [Optional].
        type: The type of this ResourceRelationship [Optional].
    """

    id: Optional[str] = None
    href: Optional[AnyUrl] = None
    relationship_type: str
    resource: ResourceRefOrValue
    base_type: Optional[str] = None
    schema_location: Optional[AnyUrl] = None
    type: Optional[str] = None

from openapi_server.models.resource_ref_or_value import ResourceRefOrValue
ResourceRelationship.update_forward_refs()
