# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401

import enum

class  ResourceStatusTypeEnum(enum.Enum):
    standby="standby"
    alarm="alarm"
    available="available"
    reserved="reserved"
    unknown="unknown"
    suspended="suspended"
   

class  ResourceStatusTypeEnum(enum.Enum):
    standby="standby"
    alarm="alarm"
    available="available"
    reserved="reserved"
    unknown="unknown"
    suspended="suspended"
   

class ResourceStatusType(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ResourceStatusType - a model defined in OpenAPI

    """


ResourceStatusType.update_forward_refs()
